version: '2.2'
services:
  qepon_database:
    image:          postgres:11
    container_name: konglomerat_database
    restart:        always
    environment:
      POSTGRES_USER:     konglomerat
      POSTGRES_PASSWORD: konglomerat
      POSTGRES_DB:       konglomerat
    ports:
      - '5432:5432'
  qepon_message_store:
    image:          postgres:11
    container_name: konglomerat_message_store
    restart:        always
    environment:
      POSTGRES_USER:     konglomerat
      POSTGRES_PASSWORD: konglomerat
      POSTGRES_DB:       konglomerat
    ports:
      - '5433:5432'
  qepon_abuse_database:
    image:          postgres:11
    container_name: konglomerat_abuse_database
    restart:        always
    environment:
      POSTGRES_USER:     konglomerat
      POSTGRES_PASSWORD: konglomerat
      POSTGRES_DB:       konglomerat
    ports:
      - '5434:5432'
  redis_master:
    image: redis:5
    container_name: redis_master
    ports:
      - '6379:6379'
  redis_slave:
    image: redis:5
    container_name: redis_slave
    command: redis-server --port 6380 --slaveof "${EXTERNAL_HOST}" 6379 --slave-announce-ip "${EXTERNAL_HOST}"
    ports:
      - '6380:6380'
  sentinel:
    build: ./sentinel
    container_name: redis_sentinel
    ports:
      - '26379:26379'
    environment:
      - SENTINEL_NAME=mysentinel
      - HOST_IP="${EXTERNAL_HOST}"
